version: '2'
services:
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "8080:80"
    expose:
      - "80"
    volumes_from:
      - web

  web:
    restart: always
    image: python:2.7
    command: run.sh
    environment:
      - DJANGO_SETTINGS_MODULE=jiller_manager.settings
    volumes:
      - .:/jiller_manager
    ports:
      - "8000:8000"
    depends_on:
      - db
