version: '2'
services:
  db:
    restart: always
    image: postgres:latest

  web:
    restart: always
    image: python:2.7
    command: !!some_command!!
    environment:
     - DJANGO_SETTINGS_MODULE=jiller_manager.settings
    volumes:
      - .:/{{name}}
    ports:
      - "8000:8000"
    depends_on:
      - db
