version: '2'
services:
  db:
    restart: always
    image: postgres:latest

  web:
    restart: always
    image: python:2.7
    command: gunicorn jiller_manager.wsgi
    environment:
     - DJANGO_SETTINGS_MODULE={{name}}.settings
    volumes:
      - .:/{{name}}
    ports:
      - "8000:8000"
    depends_on:
      - db
